//node {
//    try {
//        stage('scm checkout') {
//            checkout scm
//        }
//        stage('build') {
//            def mvnHome = tool name: 'Maven 3.5.0', type: 'maven'
//            sh "${mvnHome}/bin/mvn clean install -DskipTests"
//        }
//        stage('tests') {
//            def mvnHome = tool name: 'Maven 3.5.0', type: 'maven'
//            sh "${mvnHome}/bin/mvn clean install -Dmaven.test.failure.ignore=true"
//            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
//
//        }
//    }
//    catch (err) {
//        emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
//                Check console output at $BUILD_URL to view the results.
//                ${BUILD_LOG}  ${err}''',
//                subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!',
//                to: 'suryanshbhadouria@gmail.com'
//    }
//}
def helpers

node {
    try {
        stage('initialization') {
            echo 'scm checkout'
            checkout scm
            echo 'loading file Helpers.groovy'
            def file = findFiles(glob: '**/Helpers.groovy')
            helpers = load(file[0].getPath())
        }
        stage('build') {
            echo 'generating build while skipping tests'
            def mvnHome = tool name: 'Maven 3.5.0', type: 'maven'
            sh "${mvnHome}/bin/mvn clean install -DskipTests"
        }
        stage('tests') {
            echo 'running helpers.runTests()'
            helpers.runTests()
        }
    }
    catch (err) {
        emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
                Check console output at $BUILD_URL to view the results.
                ${BUILD_LOG}  ${err}''',
                subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!',
                to: 'suryanshbhadouria@gmail.com'
    }
}

