node {
    try {
        stage('scm checkout') {
            checkout scm
        }
        stage('build') {
            def mvnHome = tool name: 'Maven 3.5.0', type: 'maven'
            sh "${mvnHome}/bin/mvn clean install -DskipTests"
        }
        stage('tests') {
            def mvnHome = tool name: 'Maven 3.5.0', type: 'maven'
            sh "${mvnHome}/bin/mvn clean install -Dmaven.test.failure.ignore=true"
            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])

        }
    }
    catch (err) {
        emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
                Check console output at $BUILD_URL to view the results.
                ${BUILD_LOG}  ${err}''',
                subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!',
                to: 'suryanshbhadouria@gmail.com'
    }
}